/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ManageAdmin;

/**
 *
 * @author herikahareshkoshti
 */
public class ManageProject extends javax.swing.JPanel {

    /**
     * Creates new form ManageProject
     */
    public ManageProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProjLbl = new javax.swing.JLabel();
        lblProjName = new javax.swing.JLabel();
        lblSkillsReq = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        btnSubmitManageProj = new javax.swing.JButton();
        txtProjName = new javax.swing.JTextField();
        txtSkillsReq = new javax.swing.JTextField();
        txtBudget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageProj = new javax.swing.JTable();
        btnBackManageProj = new javax.swing.JButton();
        btnUpdateManageProj = new javax.swing.JButton();
        btnSaveManageProj = new javax.swing.JButton();
        btnDeleteManageProj = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        addProjLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addProjLbl.setText("Add a Project");

        lblProjName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblProjName.setText("Project Name:");

        lblSkillsReq.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblSkillsReq.setText("Skills Required:");

        lblBudget.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblBudget.setText("Budget:");

        btnSubmitManageProj.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnSubmitManageProj.setText("Submit");
        btnSubmitManageProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitManageProjActionPerformed(evt);
            }
        });

        tblManageProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblManageProj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Project Name", "Skills Required", "Budget"
            }
        ));
        jScrollPane1.setViewportView(tblManageProj);

        btnBackManageProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBackManageProj.setText("<< Back");

        btnUpdateManageProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdateManageProj.setText("Update");

        btnSaveManageProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaveManageProj.setText("Save");

        btnDeleteManageProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteManageProj.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(addProjLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProjName)
                            .addComponent(lblSkillsReq)
                            .addComponent(lblBudget))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProjName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtSkillsReq)
                            .addComponent(txtBudget)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnBackManageProj)
                        .addGap(86, 86, 86)
                        .addComponent(btnUpdateManageProj)
                        .addGap(92, 92, 92)
                        .addComponent(btnDeleteManageProj)
                        .addGap(102, 102, 102)
                        .addComponent(btnSaveManageProj)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmitManageProj, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(363, 363, 363))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(addProjLbl)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjName)
                    .addComponent(txtProjName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkillsReq)
                    .addComponent(txtSkillsReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudget)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSubmitManageProj)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackManageProj)
                    .addComponent(btnUpdateManageProj)
                    .addComponent(btnSaveManageProj)
                    .addComponent(btnDeleteManageProj))
                .addGap(136, 136, 136))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitManageProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitManageProjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitManageProjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProjLbl;
    private javax.swing.JButton btnBackManageProj;
    private javax.swing.JButton btnDeleteManageProj;
    private javax.swing.JButton btnSaveManageProj;
    private javax.swing.JButton btnSubmitManageProj;
    private javax.swing.JButton btnUpdateManageProj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblProjName;
    private javax.swing.JLabel lblSkillsReq;
    private javax.swing.JTable tblManageProj;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtProjName;
    private javax.swing.JTextField txtSkillsReq;
    // End of variables declaration//GEN-END:variables
}
